services:
  web:
    container_name: book-service
#    build:
#      context: .
    image: yfakih/tp5:latest
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: doc
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book-management?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SERVER_PORT: 8090
    ports:
      - 8090:8090
    networks:
       - network

  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: book-management
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - network


networks:
  network:
    driver: bridge
volumes:
  mysql-data: