server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book-management?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update