server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/book-management?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.jdbc.Driver
    username: user
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    web:
      pageable:
        default-page-size: 20
    jdbc:
      dialect: mysql